name: Deploy to AWS EC2

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/my-react-app:latest

    - name: Deploy to EC2
      env:
        HOST: ${{ secrets.AWS_EC2_HOST }}
        USER: ${{ secrets.AWS_EC2_USER }}
        KEY: ${{ secrets.AWS_EC2_KEY }}
        IMAGE: ${{ secrets.DOCKER_USERNAME }}/my-react-app:latest
      run: |
        echo -e "$KEY" > key.pem
        chmod 400 key.pem
        ssh -o StrictHostKeyChecking=no -i key.pem $USER@$HOST << EOF
          docker pull $IMAGE
          docker stop my-react-app || true
          docker rm my-react-app || true
          docker run -d -p 80:80 --name my-react-app $IMAGE
        EOF
